### ISSUE TITLE
[feature] have support to jump to path on click ?

### ISSUE THREAD

**Issue by ctf0** [stevenhankin/jasper#3]
**Is your feature request related to a problem? Please describe.**
no

**Additional context**
the feature concise of 2 steps
1. copy the file path along with json path: like https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line but instead of line number, we use the json path
2. add a jump to path in file on click: kinda like https://marketplace.visualstudio.com/items?itemName=ctf0.jump-to-line-number

**Comment by stevenhankin** [comment]
Hi @ctf0   👋 

Sure, that sounds like a good idea.  Would you like to raise me a PR?

**Comment by ctf0** [comment]
unfortunately i don't have enough time atm, but will keep it on my radar.

**Comment by stevenhankin** [comment]
Copy Path is now implemented in [v1.3.1](https://github.com/stevenhankin/jasper/releases/tag/v1.3.1) (but not the Jump To Path feature)
